server:
  port: 19092
spring:
  profiles:
    active: dev
  application:
    name: order-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    loadbalancer:
      ribbon:
        enabled: true
    ribbon:
      product-service:
        listOfServers: "localhost:19093,localhost:19094"
        NIWSServerListClassName: "com.netflix.loadbalancer.ConfigurationBasedServerList"
        weightedList:
          - server: "localhost:19093"
            weight: 70
          - server: "localhost:19094"
            weight: 30
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

management:
  endpoints:
    web:
      exposure:
        include: refresh
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

message: "default message"
